title: <p align="center"> Philip Wong </p>

logo: "/images/headshot.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/philip-kf-wong/">LinkedIn</a> |
  <a href="https://github.com/philipkfw">GitHub</a>
  </p>
  
  <p align="justify"> 
  I'm currently a Senior Data Analyst at Kijiji who focuses on building data extraction pipelines (ETL) and business intelligence (BI) dashboards to support revenue growth for Kijiji's commercial verticals.     
  <br><br>
  SQL | Python | R | Tableau | Databricks 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
