title: <p align="center"> Philip Wong </p>

logo: "/images/headshot.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/philip-kf-wong/">LinkedIn</a> |
  <a href="https://github.com/philipkfw">GitHub</a>
  </p>
  
  <p align="justify"> 
  I'm currently a Data Analyst at Kijiji Canada with a focus on prescriptive analytics and data visualizations.   
  <br><br>
  SQL | R | Python | Tableau | AB Testing 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
