title: <p align="center"> Philip Wong </p>

logo: "/images/headshot.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/philip-kf-wong/">LinkedIn</a> |
  <a href="https://github.com/philipkfw">GitHub</a>
  </p>
  
  <p align="justify">
  Data Analyst @ Kijiji Canada, BCom Graduate @ Queen's University, Smith School of Business
  <br><br>
  R | Python | SQL | Tableau | Google Data Studio | Excel
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
