title: <p align="center"> Philip Wong </p>

logo: "/images/headshot.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/philip-kf-wong/">LinkedIn</a> |
  <a href="https://github.com/philipkfw">GitHub</a>
  </p>
  
  <p align="justify"> 
  I'm currently a **Data Analyst** at Kijiji focusing on building data extraction pipelines (ETL) and BI tooling (dashboards) - supporting revenue growth and maintaining Kijiji's position as the #1 marketplace in Canada.     
  <br><br>
  SQL | Python | R | Tableau | Excel 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
