title: <p align="center"> Philip Wong </p>

logo: "/images/headshot.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/philip-kf-wong/">LinkedIn</a> |
  <a href="https://github.com/philipkfw">GitHub</a>
  </p>
  
  <p align="justify"> 
  I'm currently a Data Analyst at Carbon6 who focuses on data architecture and analytics engineering covering the entire data value chain from data collection, data modelling, and reverse ETL!     
  <br><br>
  SQL | Python | Apache Airflow | Tableau | Amazon Web Services (AWS)
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
